import type { IrField, NordixIr } from '../../../core/ir/types.js';

export function generateDrizzleSchemaCode(ir: NordixIr): string {
  const lines: string[] = [
    '// Generated by NordixGen - DO NOT EDIT MANUALLY',
    "import { pgTable, text, varchar, integer, doublePrecision, boolean, timestamp, uuid, pgEnum } from 'drizzle-orm/pg-core';",
    "import { relations } from 'drizzle-orm';",
    '',
  ];

  // 1. Generate Enums
  for (const [enumName, values] of Object.entries(ir.enums)) {
    const formattedValues = values.map((v) => `'${v}'`).join(', ');
    lines.push(
      `export const ${enumName}Enum = pgEnum('${enumName.toLowerCase()}', [${formattedValues}]);`,
    );
  }
  if (Object.keys(ir.enums).length > 0) lines.push('');

  // 2. Generate Tables
  for (const entity of Object.values(ir.entities)) {
    lines.push(`export const ${entity.tableName} = pgTable('${entity.tableName}', {`);

    for (const field of Object.values(entity.fields)) {
      lines.push(`  ${field.name}: ${mapFieldToDrizzleColumn(field, ir)},`);
    }

    lines.push('});');
    lines.push('');
  }

  // 3. Generate Relations
  for (const entity of Object.values(ir.entities)) {
    const relEntries = Object.values(entity.relations);
    if (relEntries.length === 0) continue;

    lines.push(
      `export const ${entity.tableName}Relations = relations(${entity.tableName}, ({ one, many }) => ({`,
    );
    for (const rel of relEntries) {
      if (rel.type === 'many-to-one' || rel.type === 'one-to-one') {
        lines.push(`  ${rel.name}: one(${rel.targetTable}, {`);
        lines.push(`    fields: [${entity.tableName}.${rel.foreignKeyColumn ? rel.name : 'id'}],`);
        lines.push(`    references: [${rel.targetTable}.${rel.targetKeyColumn}],`);
        lines.push('  }),');
      } else if (rel.type === 'one-to-many') {
        lines.push(`  ${rel.name}: many(${rel.targetTable}),`);
      }
    }
    lines.push('}));');
    lines.push('');
  }

  return lines.join('\n');
}

function mapFieldToDrizzleColumn(field: IrField, ir: NordixIr): string {
  let colDef = '';

  if (field.isPrimaryKey) {
    return `uuid('${field.columnName}').primaryKey().defaultRandom()`;
  }

  switch (field.type) {
    case 'string':
      colDef = `varchar('${field.columnName}', { length: 255 })`;
      break;
    case 'number':
      colDef = `doublePrecision('${field.columnName}')`;
      break;
    case 'boolean':
      colDef = `boolean('${field.columnName}')`;
      break;
    case 'date':
      colDef = `timestamp('${field.columnName}', { withTimezone: true, mode: 'date' })`;
      break;
    case 'uuid':
      colDef = `uuid('${field.columnName}')`;
      break;
    case 'json':
      colDef = `text('${field.columnName}')`;
      break;
    case 'enum':
      if (field.enumName && ir.enums[field.enumName]) {
        colDef = `${field.enumName}Enum('${field.columnName}')`;
      } else {
        colDef = `varchar('${field.columnName}', { length: 100 })`;
      }
      break;
    default:
      colDef = `text('${field.columnName}')`;
  }

  if (field.required) {
    colDef += '.notNull()';
  }

  if (field.unique) {
    colDef += '.unique()';
  }

  if (field.default !== undefined) {
    if (typeof field.default === 'string') {
      colDef += `.default('${field.default}')`;
    } else if (typeof field.default === 'boolean' || typeof field.default === 'number') {
      colDef += `.default(${field.default})`;
    }
  }

  return colDef;
}

export function generateDrizzleClientCode(): string {
  return `import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import * as schema from './schema.js';

export function createDb(databaseUrl: string) {
  const sql = neon(databaseUrl);
  return drizzle(sql, { schema });
}

export type DatabaseInstance = ReturnType<typeof createDb>;
`;
}
