import type { IrEntity, IrField, NordixIr } from '../../../core/ir/types.js';

export function generateSeedersCode(ir: NordixIr): string {
  const tableImports = Object.values(ir.entities)
    .map((e) => e.tableName)
    .join(', ');

  const seedBlocks: string[] = [];

  for (const entityName of ir.sortedEntityNames) {
    const entity = ir.entities[entityName];
    if (!entity) continue;

    seedBlocks.push(`
  console.log('Seeding ${entityName} records...');
  const ${entity.tableName}Ids: string[] = [];
  for (let i = 0; i < 10; i++) {
    const [inserted] = await db.insert(${entity.tableName}).values({
${generateFakerFields(entity, ir)}
    }).returning({ id: ${entity.tableName}.id });
    if (inserted?.id) ${entity.tableName}Ids.push(inserted.id);
  }
`);
  }

  return `/**
 * Database Seeder Script (Faker.js)
 * Automatically generated by NordixGen adhering to topological FK order
 */

import { faker } from '@faker-js/faker';
import { createDb } from './index.js';
import { ${tableImports} } from './schema.js';

async function main() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error('DATABASE_URL is not set');
    process.exit(1);
  }

  const db = createDb(databaseUrl);
  console.log('Starting database seeding...');
${seedBlocks.join('')}
  console.log('Database seeding completed successfully!');
}

main().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
`;
}

function generateFakerFields(entity: IrEntity, ir: NordixIr): string {
  const lines: string[] = [];
  const fields = Object.values(entity.fields).filter((f) => !f.isPrimaryKey && !f.isSystemAudit);

  for (const field of fields) {
    // If it's a foreign key referencing a parent entity, pick random UUID
    if (field.name.endsWith('Id')) {
      lines.push(`      ${field.name}: faker.string.uuid(),`);
      continue;
    }

    lines.push(`      ${field.name}: ${getFakerExpression(field, ir)},`);
  }

  return lines.join('\n');
}

function getFakerExpression(field: IrField, ir: NordixIr): string {
  const lowerName = field.name.toLowerCase();

  if (lowerName.includes('email')) return 'faker.internet.email()';
  if (lowerName.includes('name') || lowerName.includes('title'))
    return 'faker.commerce.productName()';
  if (lowerName.includes('description')) return 'faker.commerce.productDescription()';
  if (lowerName.includes('price') || lowerName.includes('total') || lowerName.includes('amount')) {
    return 'parseFloat(faker.commerce.price({ min: 10, max: 500 }))';
  }

  switch (field.type) {
    case 'string':
      return 'faker.lorem.words(3)';
    case 'number':
      return 'faker.number.int({ min: 1, max: 100 })';
    case 'boolean':
      return 'faker.datatype.boolean()';
    case 'date':
      return 'faker.date.recent()';
    case 'uuid':
      return 'faker.string.uuid()';
    case 'enum': {
      const enumVals = field.enumName ? ir.enums[field.enumName] : undefined;
      if (enumVals && enumVals.length > 0 && enumVals[0]) {
        return `'${enumVals[0]}'`;
      }
      return "'ACTIVE'";
    }
    default:
      return 'faker.lorem.word()';
  }
}
