import { type ConfigDiagnostic, createDiagnostic } from "../../diagnostics.js";
import type { FieldDefinition, NordixConfig } from "../schema.js";

function defaultMatchesFieldType(
  field: FieldDefinition,
  value: unknown,
  enumValues: string[],
): boolean {
  switch (field.type) {
    case "string":
      return typeof value === "string";
    case "number":
      return typeof value === "number" && Number.isFinite(value);
    case "boolean":
      return typeof value === "boolean";
    case "date":
      return typeof value === "string" && !Number.isNaN(Date.parse(value));
    case "uuid":
      return (
        typeof value === "string" &&
        /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
      );
    case "json":
      return value !== undefined;
    case "enum":
      return typeof value === "string" && enumValues.includes(value);
  }
}

export function validateEntities(config: NordixConfig): ConfigDiagnostic[] {
  const fieldDiagnostics: ConfigDiagnostic[] = [];
  const relationDiagnostics: ConfigDiagnostic[] = [];
  const generatedFieldDiagnostics: ConfigDiagnostic[] = [];

  for (const [entityName, entity] of Object.entries(config.entities)) {
    const generatedFields = new Set(["id"]);
    if (entity.timestamps) {
      generatedFields.add("createdAt");
      generatedFields.add("updatedAt");
    }
    if (entity.softDelete) generatedFields.add("deletedAt");

    for (const [fieldName, field] of Object.entries(entity.fields)) {
      const fieldPath = `entities.${entityName}.fields.${fieldName}`;
      if (generatedFields.has(fieldName)) {
        generatedFieldDiagnostics.push(
          createDiagnostic(
            "RESERVED_GENERATED_FIELD",
            fieldPath,
            `Field "${fieldName}" is generated by NordixGen and must not be declared manually.`,
          ),
        );
      }
      if (field.type === "enum" && !config.enums[field.enumName]) {
        fieldDiagnostics.push(
          createDiagnostic(
            "UNKNOWN_ENUM",
            `${fieldPath}.enumName`,
            `Enum "${field.enumName}" is not defined under enums.`,
          ),
        );
      }
      if (field.default !== undefined) {
        const enumValues = field.type === "enum" ? (config.enums[field.enumName] ?? []) : [];
        if (!defaultMatchesFieldType(field, field.default, enumValues)) {
          fieldDiagnostics.push(
            createDiagnostic(
              "INVALID_FIELD_DEFAULT",
              `${fieldPath}.default`,
              `Default value does not match field type "${field.type}"${field.type === "enum" ? ` or is not a member of enum "${field.enumName}"` : ""}.`,
            ),
          );
        }
      }
    }

    const fieldNames = new Set(Object.keys(entity.fields));
    for (const [relationName, relation] of Object.entries(entity.relations)) {
      const relationPath = `entities.${entityName}.relations.${relationName}`;
      if (!config.entities[relation.target]) {
        relationDiagnostics.push(
          createDiagnostic(
            "UNKNOWN_RELATION_TARGET",
            `${relationPath}.target`,
            `Entity "${relation.target}" is not defined.`,
          ),
        );
      }
      if (fieldNames.has(relationName)) {
        relationDiagnostics.push(
          createDiagnostic(
            "DUPLICATE_ENTITY_MEMBER",
            relationPath,
            `"${relationName}" is already declared as a field on entity "${entityName}".`,
          ),
        );
      }
      if (relation.onDelete === "set-null" && relation.required) {
        relationDiagnostics.push(
          createDiagnostic(
            "INVALID_SET_NULL_RELATION",
            `${relationPath}.onDelete`,
            "A required relation cannot use onDelete: set-null; mark it optional or choose another delete policy.",
          ),
        );
      }
      if (relation.type === "many-to-many" && relation.foreignKey) {
        relationDiagnostics.push(
          createDiagnostic(
            "INVALID_MANY_TO_MANY_FOREIGN_KEY",
            `${relationPath}.foreignKey`,
            "Many-to-many relations use a join table and cannot declare a single foreignKey.",
          ),
        );
      }
    }
  }

  return [...fieldDiagnostics, ...relationDiagnostics, ...generatedFieldDiagnostics];
}
