export function getStarterYamlTemplate(projectName = 'my-nordix-app'): string {
  return `# yaml-language-server: $schema=./nordix.schema.json
name: ${projectName}
version: 0.1.0
description: "Generated by NordixGen - Full-Stack Architecture on Cloudflare Edge"
structure: monorepo

frontend:
  framework: nextjs
  type: web
  styling: tailwind
  stateManagement: zustand
  authUI: true

backend:
  framework: hono
  architecture: clean
  auth:
    type: jwt
    providers: [credentials]
    twoFactor: false
    passwordRecovery: true
    roles: [admin, member]

database:
  engine: postgres
  provider: neon
  orm: drizzle

docker:
  postgres: true
  mailpit: true
  minio: true
  redis: false

llm:
  enabled: true
  exposeUseCases: true
  endpoint: /api/agent

deployment:
  provider: cloudflare
  ci: github-actions

enums:
  ProductStatus: [DRAFT, ACTIVE, ARCHIVED]
  OrderStatus: [PENDING, PAID, SHIPPED, CANCELLED]

entities:
  Product:
    description: "Store product inventory"
    fields:
      name:
        type: string
        required: true
      price:
        type: number
        required: true
      description:
        type: string
        required: false
      status:
        type: enum
        enumName: ProductStatus
    softDelete: true
    timestamps: true

  Order:
    description: "Customer purchasing order"
    fields:
      total:
        type: number
        required: true
      status:
        type: enum
        enumName: OrderStatus
    relations:
      product:
        type: many-to-one
        target: Product
        onDelete: cascade
    softDelete: true
    timestamps: true
`;
}
